language: node_js
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
node_js:
  - "6"
install:
  - npm install
script:
  - "if [ $TRAVIS_BRANCH != 'master' ]; then make neuron; fi"
after_success:
  - git fetch origin
  - git rebase origin/${TRAVIS_BRANCH}
  - "if [ $TRAVIS_BRANCH != 'master' ]; then git push ${UPSTREAM} travis:${TRAVIS_BRANCH} >/dev/null 2>/dev/null; fi"
